import type { Metadata } from "next";
import "./globals.css";
import "./flexbox.css";

export const metadata: Metadata = {
  title: "Jayson Mourier - Développeur mobile et web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
      </body>
    </html>
  );
}
